from __future__ import annotations

# CohOS-canonical reason codes (minimal set for Milestone 1).
ALLOW_ALL_CHECKS_PASS = "ALLOW_ALL_CHECKS_PASS"
COHERENCE_ENVELOPE_FAIL = "COHERENCE_ENVELOPE_FAIL"
INSTRUMENT_NOT_IN_SPEC = "INSTRUMENT_NOT_IN_SPEC"
INTERNAL_ERROR_STEP_FAIL = "INTERNAL_ERROR_STEP_FAIL"
POLICY_INVALID = "POLICY_INVALID"
